import { TabloqueState } from '../types';

export const INITIAL_STATE: TabloqueState = {
  pages: {
    'page-1': {
      id: 'page-1',
      title: 'Daily Cockpit',
      icon: 'LayoutDashboard',
      boardIds: ['board-1', 'board-2', 'board-3'],
      createdAt: Date.now() - 30000,
    },
    'page-2': {
      id: 'page-2',
      title: 'Dev & Design',
      icon: 'Code2',
      boardIds: ['board-4', 'board-5'],
      createdAt: Date.now() - 20000,
    },
  },
  boards: {
    'board-1': {
      id: 'board-1',
      title: 'Daily Essentials',
      color: 'indigo',
      bookmarkIds: ['bm-1', 'bm-2', 'bm-3', 'bm-4'],
      createdAt: Date.now() - 29000,
    },
    'board-2': {
      id: 'board-2',
      title: 'Dev Stack',
      color: 'emerald',
      bookmarkIds: ['bm-5', 'bm-6', 'bm-7'],
      createdAt: Date.now() - 28000,
    },
    'board-3': {
      id: 'board-3',
      title: 'AI & Research',
      color: 'purple',
      bookmarkIds: ['bm-8', 'bm-9', 'bm-10'],
      createdAt: Date.now() - 27000,
    },
    'board-4': {
      id: 'board-4',
      title: 'UI Inspiration',
      color: 'amber',
      bookmarkIds: ['bm-11', 'bm-12', 'bm-13'],
      createdAt: Date.now() - 19000,
    },
    'board-5': {
      id: 'board-5',
      title: 'Tech News & Blogs',
      color: 'rose',
      bookmarkIds: ['bm-14', 'bm-15'],
      createdAt: Date.now() - 18000,
    },
  },
  bookmarks: {
    'bm-1': {
      id: 'bm-1',
      title: 'GitHub',
      url: 'https://github.com',
      description: 'Code repositories and collaboration',
      createdAt: Date.now() - 26000,
    },
    'bm-2': {
      id: 'bm-2',
      title: 'Linear',
      url: 'https://linear.app',
      description: 'Issue tracker and project roadmap',
      createdAt: Date.now() - 25000,
    },
    'bm-3': {
      id: 'bm-3',
      title: 'Notion',
      url: 'https://notion.so',
      description: 'Connected workspace for notes and docs',
      createdAt: Date.now() - 24000,
    },
    'bm-4': {
      id: 'bm-4',
      title: 'Google Calendar',
      url: 'https://calendar.google.com',
      description: 'Schedule, agenda, and meetings',
      createdAt: Date.now() - 23000,
    },
    'bm-5': {
      id: 'bm-5',
      title: 'Tailwind CSS Docs',
      url: 'https://tailwindcss.com/docs',
      description: 'Utility-first CSS framework documentation',
      createdAt: Date.now() - 22000,
    },
    'bm-6': {
      id: 'bm-6',
      title: 'Vite Guide',
      url: 'https://vitejs.dev',
      description: 'Next generation frontend tooling',
      createdAt: Date.now() - 21000,
    },
    'bm-7': {
      id: 'bm-7',
      title: 'MDN Web Docs',
      url: 'https://developer.mozilla.org',
      description: 'Resources for developers, by developers',
      createdAt: Date.now() - 20000,
    },
    'bm-8': {
      id: 'bm-8',
      title: 'Claude',
      url: 'https://claude.ai',
      description: 'Anthropic AI assistant',
      createdAt: Date.now() - 17000,
    },
    'bm-9': {
      id: 'bm-9',
      title: 'ChatGPT',
      url: 'https://chatgpt.com',
      description: 'OpenAI intelligent assistant',
      createdAt: Date.now() - 16000,
    },
    'bm-10': {
      id: 'bm-10',
      title: 'Hugging Face',
      url: 'https://huggingface.co',
      description: 'Open source AI models and datasets',
      createdAt: Date.now() - 15000,
    },
    'bm-11': {
      id: 'bm-11',
      title: 'Mobbin',
      url: 'https://mobbin.com',
      description: 'Mobile & web design patterns archive',
      createdAt: Date.now() - 14000,
    },
    'bm-12': {
      id: 'bm-12',
      title: 'Dribbble',
      url: 'https://dribbble.com',
      description: 'Design inspiration and creative showcase',
      createdAt: Date.now() - 13000,
    },
    'bm-13': {
      id: 'bm-13',
      title: 'Godly Website Inspiration',
      url: 'https://godly.website',
      description: 'Curated web design gallery',
      createdAt: Date.now() - 12000,
    },
    'bm-14': {
      id: 'bm-14',
      title: 'Hacker News',
      url: 'https://news.ycombinator.com',
      description: 'Tech and startup community news',
      createdAt: Date.now() - 11000,
    },
    'bm-15': {
      id: 'bm-15',
      title: 'The Verge',
      url: 'https://theverge.com',
      description: 'Tech, science, art, and culture journalism',
      createdAt: Date.now() - 10000,
    },
  },
  pageOrder: ['page-1', 'page-2'],
  activePageId: 'page-1',
  privacyMode: false,
  theme: 'emerald',
  typography: {
    fontFamily: 'inter',
    fontSize: 'medium',
    fontWeight: 'medium',
    textTransform: 'none',
    textColor: '#ffffff',
    letterSpacing: 'normal',
  },
  borderConfig: {
    style: 'subtle',
    accentGlow: false,
  },
  watches: {
    'watch-1': {
      id: 'watch-1',
      type: 'hybrid',
      is24Hour: false,
      showSeconds: true,
      position: { x: 24, y: 16 },
      createdAt: Date.now() - 30000,
    },
  },
  watchOrder: ['watch-1'],
  calendars: {},
  calendarOrder: [],
  activeTab: 'bookmarks',
  authBoards: {
    'auth-board-1': {
      id: 'auth-board-1',
      title: 'Dev & Cloud Accounts',
      color: 'emerald',
      authItemIds: ['auth-item-1', 'auth-item-2'],
      createdAt: Date.now() - 25000,
    },
  },
  authItems: {
    'auth-item-1': {
      id: 'auth-item-1',
      title: 'GitHub',
      url: 'https://github.com/login',
      userId: 'hannan_developer',
      password: 'ghp_SampleSecretToken123456',
      notes: 'Primary dev account',
      createdAt: Date.now() - 24000,
    },
    'auth-item-2': {
      id: 'auth-item-2',
      title: 'Vercel Dashboard',
      url: 'https://vercel.com/login',
      userId: 'hannan@tabloque.dev',
      password: 'Vercel#SecurePassword2026',
      notes: 'Production deployments',
      createdAt: Date.now() - 23000,
    },
  },
  authBoardOrder: ['auth-board-1'],
  noteBoards: {
    'note-board-1': {
      id: 'note-board-1',
      title: 'Quick Scratchpad',
      color: 'purple',
      noteItemIds: ['note-item-1'],
      createdAt: Date.now() - 20000,
    },
  },
  noteItems: {
    'note-item-1': {
      id: 'note-item-1',
      title: 'TabLoque Roadmap',
      content: '1. Glassmorphism navigation tabs\n2. One-click credential copy on link launch\n3. Responsive notes cards',
      color: 'emerald',
      isPinned: true,
      createdAt: Date.now() - 19000,
      updatedAt: Date.now() - 19000,
    },
  },
  noteBoardOrder: ['note-board-1'],
  firebaseConfig: null,
  lastSyncedAt: null,
  customThemeColor: null,
  customBackgroundImage: null,
  backgroundBlur: 0,
  backgroundBrightness: 100,
  cardGlassBlur: 4,
  cardGlassOpacity: 25,
};
